config/routes.rb
Rails.application.routes.draw do
  root 'bills#index'

  devise_for :users
  resources :savings
  resources :bills
  resources :incomes

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :user
end

app/models/income.rb
class Income < ActiveRecord::Base
	belongs_to :user
end

app/models/saving.rb
class Saving < ActiveRecord::Base
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :bills
    has_many :incomes
    has_many :savings
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
    @savings = Saving.all
    @incomes = Income.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  @bills = Bill.all
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_path, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_path, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:title, :pro_cost, :act_cost, :user_id, :act_income)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]


  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to bills_path, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to bills_path, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:title, :pro_income, :act_income, :income_id)
    end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: [:show, :edit, :update, :destroy]

  # GET /savings
  # GET /savings.json
  def index
    @savings = Saving.all
  end

  # GET /savings/1
  # GET /savings/1.json
  def show
  end

  # GET /savings/new
  def new
    @saving = Saving.new
  end

  # GET /savings/1/edit
  def edit
  end

  # POST /savings
  # POST /savings.json
  def create
    @saving = Saving.new(saving_params)

    respond_to do |format|
      if @saving.save
        format.html { redirect_to bills_path, notice: 'Saving was successfully created.' }
        format.json { render :show, status: :created, location: @saving }
      else
        format.html { render :new }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savings/1
  # PATCH/PUT /savings/1.json
  def update
    respond_to do |format|
      if @saving.update(saving_params)
        format.html { redirect_to bills_path, notice: 'Saving was successfully updated.' }
        format.json { render :show, status: :ok, location: @saving }
      else
        format.html { render :edit }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savings/1
  # DELETE /savings/1.json
  def destroy
    @saving.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Saving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saving
      @saving = Saving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saving_params
      params.require(:saving).permit(:title, :balance, :goal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-inline" role="form">
 <div class="form-group">
    <%= f.label :title, class: "sr-only" %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter Business Name" %>
  </div>
<br>
  <div class="form-group">
    <%= f.label :pro_cost, class: "sr-only" %><br>
    <%= f.text_area :pro_cost, class: "form-control", placeholder: "Projected Cost" %>
  </div>
  <br>
    <div class="form-group">
    <%= f.label :act_cost, class: "sr-only" %><br>
    <%= f.text_area :act_cost, class: "form-control", placeholder: "Actual Cost" %>
  </div>
  <br>
   <div class="cant-see-me">
    <%= f.number_field :bill_id, value: @bill.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bills/_form2.html.erb
<br>
<table class="table">
  <tbody>
    <tr> 
<% @bills.each do |bill| %>
    <td style="width:25%"><%= link_to bill.title, bill %></td>
    <td style="width:25%"><%= bill.pro_cost %></td>
    <td style="width:25%"><%= bill.act_cost %></td>

    <td style="width:25%"><%= form_for bill do |f| %>
        <%= f.text_area :act_cost, class: "form-control", placeholder: "Actual Cost" %>
      
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </td>
</tr>
</tbody>
<% end %>
</table>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <table class="table">
    <h4>Income</h4>
    <%= link_to 'New Income', new_income_path %>
    <br>
      <thead>
        <tr>
          <th style="width:25%">Source</th>
          <th style="width:25%">Projected Amount</th>
           <th style="width:25%">Actual Amount</th>
           <th style="width:25%"></th>
        </tr>
      </thead>
      <%= render 'incomes/form2' %>
</div> 
<div class="row">
  <div class="col-xs-4">
    <h5>Total Income</h5>
  </div> 
  <div class="col-xs-4">
    <%= Income.sum(:act_income) %>
  </div>
</div>
  <div class="container">
    <table class="table">
    <h4>Bills</h4>
    <%= link_to 'New Bill', new_bill_path %><br />
    <thead>
      <tr>
        <th style="width:25%">Name</th>
        <th style="width:25%">Projected</th>
        <th style="width:25%">Actual</th>
        <th style="width:25%"></th>
      </tr>
    </thead>
    <%= render 'form2' %>
</div> 
<div class="row">
  <div class="col-xs-4">
    <h5>Total Bills</h5>
  </div> 
  <div class="col-xs-4">
    <%= Bill.sum(:act_cost) %>
  </div>
</div>
<div class="row">
   <div class="col-xs-4">
     <h5>Remaining Balance</h5>
   </div>
   <div class="col-xs-4">
      <%= Income.sum(:act_income) - Bill.sum(:act_cost) %>
   </div>  
</div>  
 

</div>  
<div class="container">
    <div class="container">
      <div>
        <h4>Savings</h4>
        <%= link_to 'New saving', new_saving_path %>
        <br>
          <div class="category">
            <div class="col-xs-2">
              <th>Name</th>
            </div>
            <div class="col-xs-2">
              <th>Balance</th>
            </div>
            <div class="col-xs-2">
              <th>Goal</th>
            </div>
            <div class="col-xs-2">
              <th>Met</th>
            </div>
          </div>
      </div>
         <div>
          <%= render 'savings/form2' %>
        </div> 
        <div class="row">
          <div class="col-xs-6">
            <h5>Balance</h5>
          </div> 
        </div>
    </div>
</div>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bill.title %>
</p>

<p>
  <strong>Projected:</strong>
  <%= @bill.pro_cost %>
</p>

<p>
  <strong>Actual:</strong>
  <%= @bill.act_cost %>
</p>
<%= link_to 'Back', bills_path %>
<%= link_to 'Edit', edit_bill_path(@bill) %>
<%= link_to 'Destroy', @bill, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :pro_income %><br>
    <%= f.text_field :pro_income %>
  </div>
    <div class="cant-see-me">
    <%= f.number_field :income_id, value: @income.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/_form2.html.erb
<br> 
<table class="table">
  <tbody>
    <tr>
<% @incomes.each do |income| %>
  
     <td style="width:25%"><%= link_to income.title, income %></td>
     <td style="width:25%"><%= income.pro_income %></td>
     <td style="width:25%"><%= income.act_income %></td>
    
      <td style="width:25%"><%= form_for income do |f| %>
        <%= f.text_area :act_income, class: "form-control", placeholder: "Actual Income" %>
      
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
        </div> 
      <% end %>
      </td>
    </tr>
  </tbody>
<% end %>
</table>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', bills_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Projected</th>
      <th>Actual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.title %></td>
        <td><%= income.pro_income %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @income.title %>
</p>

<p>
  <strong>Projected:</strong>
  <%= @income.pro_income %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', bills_path %>
<%= link_to 'Destroy', @income, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PaycheckBudget</title>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
    
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
		<%= yield %>
		</div>
	</body>
</html>

app/views/savings/_form.html.erb
<%= form_for(@saving) do |f| %>
  <% if @saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
      <% @saving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
   <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  
      <div class="cant-see-me">
    <%= f.number_field :saving_id, value: @saving.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/savings/_form2.html.erb
<br>
<div class="row">  
<% @savings.each do |saving| %>
    <div class="col-xs-2 col-sm-2">
      <%= link_to saving.title, saving %><br>
    </div>
    
    <div class="col-xs-2 col-sm-2">
      <%= saving.balance %><br>
    </div>

    <div class="col-xs-2 col-sm-2">
      <%= saving.goal %><br>
    </div>
    <div class="col-xs-2 col-sm-2">
      <%= saving.met %>
        <%= ((saving.balance/saving.goal) * 100).to_s + "%" %>
    </div>
  <br>
<% end %>
</div>

app/views/savings/edit.html.erb
<h1>Editing Saving</h1>

<%= render 'form' %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', bills_path %>

app/views/savings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Savings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savings.each do |saving| %>
      <tr>
        <td><%= saving.title %></td>
        <td><%= saving.balance %></td>
        <td><%= saving.goal %></td>
        <td><%= link_to 'Show', saving %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saving', new_saving_path %>

app/views/savings/new.html.erb
<h1>New Saving</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @saving.title %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @saving.balance %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @saving.goal %>
</p>

<%= link_to 'Edit', edit_saving_path(@saving) %> |
<%= link_to 'Back', bills_path %>
<%= link_to 'Destroy', @saving, method: :delete, data: { confirm: 'Are you sure?' } %>